### ISSUE TITLE
META: Issues to review later

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/domain#10]
This meta issue is to keep track of any PR's or changes that might need to be reviewed later. At this early stage, we're making some small changes that we are not entirely sure about and want a place to track them and review them later, before any final release. 

- [ ] https://github.com/backdrop-contrib/domain/pull/6
- [ ] D7 to B update hook needs some attention for node types - https://github.com/backdrop-contrib/domain/pull/12

**Comment by stpaultim** [comment]
This PR seems to solve an immediate problem, but we're not sure that it's the best solution. We went ahead and merged it and are listing it here for us to review later. 
https://github.com/backdrop-contrib/domain/pull/6

**Comment by yorkshire-pudding** [comment]
Should this be closed @stpaultim ?

**Comment by stpaultim** [comment]
@yorkshire-pudding Yeah, I think it would be fine to close this issue.
