### ISSUE TITLE
Domain Blocks

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/domain#17]
Get blocks working for domain. 

My colleague wrote the following. 

> I tried to port the Domain Block module into the Backdrop CMS. After some RND I realized Backdrop moved visibility conditions into the layout section.
> 
> So I added the Domain-specific visibility conditions into the Domain module using the access plugin, now you can add domain-specific visibility conditions from the layout and we do not need to convert the Domain Block module into the Backdrop CMS.

Does this make sense?

**Comment by stpaultim** [comment]
Atten @yorkshire-pudding

**Comment by izmeez** [comment]
I am assuming this was closed with this [commit](https://github.com/backdrop-contrib/domain/commit/d549dc5affb10f12c1229caac13f9b43de202972) adding support for blocks. Does this need to be added to the new 1.x-3.x branch or is it already taken care of? Does this issue need to be re-opened until confirmed?

**Comment by izmeez** [comment]
The two ports are using the same solution just at different paths.

The 1.x-3.x-old adds a new file with path `plugins/access/domain_layout_access.inc` and contents shown in [commit](https://github.com/backdrop-contrib/domain/commit/d549dc5affb10f12c1229caac13f9b43de202972#diff-91a3a0ceb67da1b426c5396529794cfc2a062f4c23cf3d9dab8d45ec3e6cdc19R8) 

while the `1.x-3.x` branch includes a new file at `/plugins/layout/access/domain_layout_access.inc` the contents of which appear to be the same.

So the question becomes what is the best path to use with or without extra nesting? Maybe less or no nesting is best? Possibly just `plugins/domain_layout_access.inc` ?
