### ISSUE TITLE
Override Site Name with Domain Name - Not Working

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/domain#21]
On the domain settings page, the first setting is to override the site name with the domain name. 

Based upon my tests, this is not working. 

![image](https://github.com/backdrop-contrib/domain/assets/3144571/8709859c-047c-43e5-a610-230431f3289f)

**Comment by izmeez** [comment]
I think this is working in the new 1.x.3.x branch. Needs confirmation.

**Comment by stpaultim** [comment]
I did a quick test as well and was unable to recreate this problem. Let's close this issue, unless it comes up again.
