### ISSUE TITLE
Review old issues from before Rodobaldo port replaced 1.x-3.x branch

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/domain#24]
Just put this issue here as a placeholder. Preceding 6 issues were reported on the earlier port that is no on branch 1.x-3.x-old and need to be reviewed to determine if they are still active issues. Thanks.

- [x] #1 
- [x] #5 
- [x] #21

**Comment by yorkshire-pudding** [comment]
All issues checked and closed.
