### ISSUE TITLE
Add domain_prefix UI functionality

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/domain#30]
Provide a user interface for enabling select database table prefixing for use with subdomains, similar to Drupal 7 domain_prefix module, http://drupal.org/project/domain_prefix.

**Comment by yorkshire-pudding** [comment]
@izmeez - I really can't see the purpose of this or any benefits of this in Backdrop's context.  If there are real use cases, then please can you articulate them.  I suspect this should be a separate module rather than part of the core Domain module.

**Comment by izmeez** [comment]
I had forgotten about this issue and started a new issue that I will close shortly with the title: Avoid porting domain_prefix module

in Drupal the `domain_prefix` module was an add-on module, not an included sub-module of the domain module. https://www.drupal.org/project/domain_prefix

The purpose of that module was to:

> Provide a user interface for enabling select database table prefixing for use with subdomains.

However, the original maintainer states he never uses it.

Also, per table prefixes was deprecated in Drupal 8.2 and dropped in Drupal 10, see https://www.drupal.org/node/2768219

> Per-table prefixes are deprecated as of Drupal 8.2, will be removed before the release of Drupal 10.0. After that, only a single prefix for all tables will be supported.

Also if someone has a use case for such a function a shortcut is available for Drupal that could be adapted for Backdrop CMS, https://www.drupal.org/node/1953292

**Comment by yorkshire-pudding** [comment]
Thanks for expanding.  I still don't know why anyone would need this.  It talks about subdomains but I think domain just handles things.  Introducing a module specific level of db prefixing seems to be storing up problems.  I'm also wary of linking to this as a possible solution as it risks creating a support nightmare if people follow it.

**Comment by izmeez** [comment]
It may be helpful to update the wiki (docs) and therein suggest that the `domain_prefix` module, which has not been ported to Backdrop should be avoided and make reference to per table prefixes have been deprecated since Drupal 8.2 and dropped in Drupal 10.

**Comment by yorkshire-pudding** [comment]
> It may be helpful to update the wiki (docs) and therein suggest that the `domain_prefix` module, which has not been ported to Backdrop should be avoided and make reference to per table prefixes have been deprecated since Drupal 8.2 and dropped in Drupal 10.

I would suggest maybe there is no need to mention it.  It almost seems like that module and the script were fixing a problem that didn't exist. I'm not aware of Backdrop having any support for 'per table prefixes' either.

**Comment by yorkshire-pudding** [comment]
> I'm not aware of Backdrop having any support for 'per table prefixes' either.

A new module has let me know that table prefixes can exist in Backdrop, so this _could_ in theory work. However:

- the db queries don't meet Backdrop CMS coding standards
- I still can't see what possible use case or benefit there is for this
- there may also be other differences between Backdrop and Drupal 7 that mean that any previous use case is no longer applicable and/or the approach is not applicable.
