### ISSUE TITLE
Does multi-language support require the Drupal 7 domain_variable module to be ported?

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/domain#34]
I have not tested multi language support in the domain module, this is a question from my research into the module.

Does the Drupal 7 [domain_variable](https://www.drupal.org/project/domain_variable) module need to be ported to Backdrop for multi-language support with domain access?

**Comment by yorkshire-pudding** [comment]
Looking at the screenshot on the page:
![image](https://github.com/user-attachments/assets/2f9c7246-7eb9-47c1-b613-3252cb97cca1)

That would appear to be the case

**Comment by yorkshire-pudding** [comment]
@izmeez - however, as in D7 it was a separate module, I think it is out of scope for this module, at least for now.  Feel free to add a port request to https://github.com/backdrop-ops/contrib/issues . If there is demand for multilingual capabilities, and it does not work with Backdrop's multi-language support, then there could even be a feature request to include here, but I think for now this is out of scope

**Comment by izmeez** [comment]
I just thought with multilingual support in Backdrop 1.29.x it would be good to know. But, I'm not the right person for this.

**Comment by yorkshire-pudding** [comment]
@izmeez - the support in 1.29.0 is for the user interface and that should work out of the box.  I think what this relates to is the [Internationalization (i18n)](https://github.com/backdrop-contrib/i18n) module.

![image](https://github.com/user-attachments/assets/358c80c0-8cd0-45b0-b474-a1a451cd45c4)

Backdrop also doesn't have a Variable module, mainly as we've moved from variables to config and states
