### ISSUE TITLE
Update comments in settings.inc file.

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/domain#37]
This issue is a follow-up to https://github.com/backdrop-contrib/domain/issues/25 

The comments in the `settings.inc` file need to be updated for Backdrop. PR to follow.

**Comment by izmeez** [comment]
The PR needs review. It includes comment updates for Backdrop, clarity, and phpcs.

**Comment by izmeez** [comment]
I wonder if the link to the drupal issue queue, https://www.drupal.org/node/1559486, should be a link to the comment adding `try` and `catch`, https://www.drupal.org/project/domain/issues/1559486#comment-10188570 that allows the `settings.inc` file to be included in the `settings.php` file even before Backdrop is installed. There are other comments in the thread that are no longer relevant.

**Comment by stpaultim** [comment]
@yorkshire-pudding This PR "Works for me" 

Does someone else want to merge it and close this issue. 

NOTE: It's late and I did not look super closely at it. But, skimming through it, the changes all seem very sensible and low risk.

**Comment by izmeez** [comment]
Should the link be updated as described in comment above https://github.com/backdrop-contrib/domain/issues/37#issuecomment-2433155454 ?

**Comment by izmeez** [comment]
@yorkshire-pudding Thank you for reviewing the PR. Changes made as per suggestions.
