### ISSUE TITLE
Installing another module using manual install with url fails

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/domain#41]
When the domain module is working, installing another module using the manual install with a url starts but hangs with `0%`. The manual install works if the domain module is disabled by commenting the include line in the `settings.php` file as in https://github.com/backdrop-contrib/domain/issues/39.

**Comment by izmeez** [comment]
PR #46 for issue #39 also appears to fix this issue.

**Comment by yorkshire-pudding** [comment]
I can not reproduce this error after applying the PR so I think we can say it is fixed.
