### ISSUE TITLE
Getting weird issues after installing Domain Path module with the newly ported domain module

### ISSUE THREAD

**Issue by sudipto68** [backdrop-contrib/domain#42]
Have anyone tried this module https://github.com/backdrop-contrib/domain_path with the newly ported domain module. The Domain Path module is used to create domain-specific alias.
If I install this module with the domain module, then both sites showing the same content, I mean domain-specific content not working.

**Comment by sudipto68** [comment]
@rudy880719 @izmeez Can you please test this with the new domain module?

**Comment by izmeez** [comment]
@sudipto68 I see that is a separate module, https://github.com/backdrop-contrib/domain_path that was ported from https://www.drupal.org/project/domain_path with a background issue at https://www.drupal.org/node/940762.

Can you provide more specific details of the steps you are doing and what you are encountering?

**Comment by izmeez** [comment]
That module has been mentioned in the wiki, https://github.com/backdrop-contrib/domain/wiki/1.-Domain-module-wiki so there is plenty of room to elaborate on how it may be useful.

**Comment by sudipto68** [comment]
@izmeez The domain path is used for domain specific path alias. In my case, I have two domains, both have about page. The first domains about page link is /about.
But for second domain is got changed to /about-1. But there is a option after installing domain path module, that is domain specific path,  from there we can define a path. For the second domain we can write here /about. 
For this, though our second domain's about page main alias is /about-1,  It will now work for the url /about. 
I think, This is how this domain path module work. 

But the problem I am facing,  If I have previously installed domain access module, then I wanted to setup the domain path module. After installing the domain path, the domain access module's functionality does not working. 

I just wanted to be sure that, if it is also happening  to you or not.

**Comment by sudipto68** [comment]
@izmeez I have found out the issue. There were some changes in the old port, so I have made a new PR on the domain_path module, now it is working fine with the domain module.

**Comment by izmeez** [comment]
@sudipto68 That's great.
