### ISSUE TITLE
Domain - Beta Release

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/domain#45]
@yorkshire-pudding, @rudy880719, @izmeez, @sudipto68 

If possible, I would like to get out a beta release of the domain module before Backdrop LIVE. Do any of you think that any of the issues in the issue queue are blockers for a beta release?

**Comment by yorkshire-pudding** [comment]
@stpaultim - I still think #39 is a blocker (hence why it has a `status - block` tag on).  Specifically, it is the inability to do updates without disabling the line in `settings.php`.  This breaks the ability to update a Backdrop site in the user interface.

**Comment by stpaultim** [comment]
> (hence why it has a status - block tag on)

;-)

Whoops. I guess I did see that, but it slipped my mind. Thanks for your patience.

**Comment by stpaultim** [comment]
It seems as if our only "blocker" has been fixed, so I went ahead and issued a beta release of the domain module. I think it would be helpful to get more eyes on this module and more testing.

**Comment by yorkshire-pudding** [comment]
Thanks @stpaultim
