### ISSUE TITLE
PHP 8.1 Creating new domain causes deprecated function warning

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/domain#47]
**Steps to reproduce**

1. Enable display of all error and warning messages.
2. Have PHP 8.1 or higher
3. Create new domain record

**Expected result**
Domain is saved with no error messages

**Actual result**
Domain is saved but error message displays:
>`Deprecated function: strcmp(): Passing null to parameter #2 ($string2) of type string is deprecated in domain_form_validate() (line 617 of /app/docroot/modules/domain/domain.admin.inc).`

**Comment by sudipto68** [comment]
@yorkshire-pudding I can reproduce this issue by following the above steps and the fix that you provide also fixes the issue. After applying the fix, the error message didn't show up anymore.

**Comment by stpaultim** [comment]
@yorkshire-pudding I went ahead and merged this PR. @sudipto68 says it looks good and works fine. 

If you were holding off for any reason, we can reverse it.

**Comment by yorkshire-pudding** [comment]
Thanks @stpaultim - no, wasn't waiting for any reason.
