### ISSUE TITLE
Create a SnapShot branch

### ISSUE THREAD

**Issue by stpaultim** [backdrop-contrib/domain#9]
While it's probably not necessary, @yorkshire-pudding and I discussed our strategy for this module today and decided to create a snapshot branch just to make it easier to revert or see the diff between where the main branch was when we started and where it currently is. 

Any questions or comments about this branch can be discussed here.

https://github.com/backdrop-contrib/domain/tree/snapshot

**Comment by yorkshire-pudding** [comment]
No longer needed
